# config/languages.py

LANGUAGES = {
    "vi": {
        "title_add": "Thêm bệnh nhân",
        "title_edit": "Sửa bệnh nhân",
        "lbl_name": "Họ tên:",
        "plh_name": "Nhập họ tên",
        "lbl_birth": "Năm sinh:",
        "plh_birth": "VD: 1990",
        "lbl_gender": "Giới tính:",
        "gender_male": "Nam",
        "gender_female": "Nữ",
        "lbl_phone": "Số điện thoại:",
        "lbl_address": "Địa chỉ:",
        "plh_address": "Địa chỉ",
        "btn_save": "Lưu",
        "btn_cancel": "Hủy",
        "err_title": "Lỗi",
        "err_empty_name": "Họ tên không được để trống",
        "err_empty_birth": "Vui lòng nhập năm sinh",
        "err_invalid_birth": "Năm sinh phải từ 1900 đến 2026",
        "err_invalid_phone": "Số điện thoại phải có đúng 10 chữ số",
        "close": "Đóng",

        # Lịch Sử Khám Bệnh
        "history_title": "Lịch sử khám bệnh",
        "lbl_visit_date": "Ngày khám (YYYY-MM-DD):",
        "lbl_height": "Chiều cao (cm):",
        "lbl_weight": "Cân nặng (kg):",
        "lbl_systolic": "HATT (mmHg):",
        "lbl_diastolic": "HATTr (mmHg):",
        "lbl_diagnosis": "Chẩn đoán:",
        "lbl_prescription": "Thuốc kê:",
        "btn_add_visit": "➕ Thêm lần khám",
        "btn_ai_advice": "🤖 Trợ lý AI Tư vấn",
        "ai_header": "💡 Khuyến nghị từ AI Agent:",
        "ai_init_status": "Hệ thống AI sẵn sàng. Nhập Chẩn đoán & Thuốc để nhận tư vấn.",
        "btn_delete_visit": "🗑️ Xóa lần khám được chọn",
        
        # Treeview Bệnh nhân
        "col_id": "Mã BN",
        "col_name": "Họ và Tên",
        "col_birth": "Năm sinh",
        "col_gender": "Giới tính",
        "col_phone": "Số điện thoại",
        "col_address": "Địa chỉ",

        # Treeview Lịch sử khám
        "col_date": "Ngày khám",
        "col_height": "Cao (cm)",
        "col_weight": "Nặng (kg)",
        "col_systolic": "HATT",
        "col_diastolic": "HATTr",
        "col_diagnosis": "Chẩn đoán",
        "col_prescription": "Thuốc kê",

        # Thêm từ khóa cho MainView để sửa lỗi chuyển đổi ngôn ngữ nóng
        "menu_hoso": "🗂️ Quản Lý Hồ Sơ",
        "menu_data": "📊 Dữ Liệu CSV",
        "menu_hethong": "⚙️ Hệ Thống",
        "btn_add": "➕ Thêm Bệnh Nhân",
        "btn_edit": "📝 Sửa Thông Tin",
        "btn_history": "📜 Lịch Sử Khám",
        "btn_delete": "🗑️ Xóa Hồ Sơ",
        "btn_import": "📥 Nhập CSV",
        "btn_export": "📤 Xuất CSV",
        "btn_template": "📋 Tải File Mẫu",
        "btn_about": "ℹ️ Giới Thiệu",
        "lbl_search_title": "🔍 Bộ lọc tìm kiếm:",
        "plh_search": "Nhập tên hoặc số điện thoại để tìm kiếm bệnh nhân...",
        "btn_search": "Tìm Kiếm",
        "btn_refresh": "Làm Mới",
        "btn_toggle_ime": "⌨️ Bộ gõ Linux",
        "theme_prefix": "Giao diện: ",

        # Thống kê Footer
        "stats_total": "Tổng số bệnh nhân: {}",
        "stats_male": "Nam: {}",
        "stats_female": "Nữ: {}",
        "stats_avg_age": "Tuổi trung bình: {:.1f}",

        # Messages
        "msg_missing_info": "Thiếu thông tin",
        "msg_enter_diagnosis": "Vui lòng nhập 'Chẩn đoán' để AI phân tích.",
        "msg_sys_error": "Lỗi hệ thống",
        "msg_no_ai_agent": "Controller chưa cấu hình AI Agent.",
        "msg_ai_processing": "🤖 AI đang phân tích dữ liệu lâm sàng, vui lòng đợi...",
        "msg_select_visit": "Chọn lần khám",
        "msg_warn_select_delete": "Vui lòng chọn một lần khám để xóa",
        "msg_confirm": "Xác nhận",
        "msg_ask_delete": "Xóa lần khám này?",
        "msg_no_ai_data": "Lượt khám này không có dữ liệu tư vấn AI cũ."
    },
    "en": {
        "title_add": "Add Patient",
        "title_edit": "Edit Patient",
        "lbl_name": "Full Name:",
        "plh_name": "Enter full name",
        "lbl_birth": "Birth Year:",
        "plh_birth": "Ex: 1990",
        "lbl_gender": "Gender:",
        "gender_male": "Male",
        "gender_female": "Female",
        "lbl_phone": "Phone Number:",
        "lbl_address": "Address:",
        "plh_address": "Address",
        "btn_save": "Save",
        "btn_cancel": "Cancel",
        "err_title": "Error",
        "err_empty_name": "Full name cannot be empty",
        "err_empty_birth": "Please enter birth year",
        "err_invalid_birth": "Birth year must be from 1900 to 2026",
        "err_invalid_phone": "Phone number must be exactly 10 digits",
        "close": "Close",

        # Medical History
        "history_title": "Medical History",
        "lbl_visit_date": "Visit Date (YYYY-MM-DD):",
        "lbl_height": "Height (cm):",
        "lbl_weight": "Weight (kg):",
        "lbl_systolic": "SBP (mmHg):",
        "lbl_diastolic": "DBP (mmHg):",
        "lbl_diagnosis": "Diagnosis:",
        "lbl_prescription": "Prescription:",
        "btn_add_visit": "➕ Add Record",
        "btn_ai_advice": "🤖 Ask AI Assistant",
        "ai_header": "💡 AI Agent Recommendations:",
        "ai_init_status": "AI System Ready. Enter Diagnosis & Prescription for guidance.",
        "btn_delete_visit": "🗑️ Delete Selected Record",
        
        # Treeview Patients
        "col_id": "ID",
        "col_name": "Full Name",
        "col_birth": "Birth Year",
        "col_gender": "Gender",
        "col_phone": "Phone Number",
        "col_address": "Address",

        # Treeview History
        "col_date": "Date",
        "col_height": "Height (cm)",
        "col_weight": "Weight (kg)",
        "col_systolic": "SBP",
        "col_diastolic": "DBP",
        "col_diagnosis": "Diagnosis",
        "col_prescription": "Prescription",

        # MainView localization
        "menu_hoso": "🗂️ Records Management",
        "menu_data": "📊 CSV Data",
        "menu_hethong": "⚙️ System Options",
        "btn_add": "➕ Add Patient",
        "btn_edit": "📝 Edit Profile",
        "btn_history": "📜 Medical History",
        "btn_delete": "🗑️ Delete Record",
        "btn_import": "📥 Import CSV",
        "btn_export": "📤 Export CSV",
        "btn_template": "📋 Get Template",
        "btn_about": "ℹ️ About App",
        "lbl_search_title": "🔍 Search Filter:",
        "plh_search": "Type name or phone to filter patients...",
        "btn_search": "Search",
        "btn_refresh": "Refresh",
        "btn_toggle_ime": "⌨️ Linux IME",
        "theme_prefix": "Theme: ",

        # Footer stats
        "stats_total": "Total Patients: {}",
        "stats_male": "Male: {}",
        "stats_female": "Female: {}",
        "stats_avg_age": "Avg Age: {:.1f}",

        # Messages
        "msg_missing_info": "Missing Information",
        "msg_enter_diagnosis": "Please enter 'Diagnosis' for AI analysis.",
        "msg_sys_error": "System Error",
        "msg_no_ai_agent": "Controller is not configured with AI Agent.",
        "msg_ai_processing": "🤖 AI is analyzing clinical data, please wait...",
        "msg_select_visit": "Select Visit",
        "msg_warn_select_delete": "Please select a medical record to delete",
        "msg_confirm": "Confirmation",
        "msg_ask_delete": "Delete this medical record?",
        "msg_no_ai_data": "This record has no old AI consultation data."
    }
}